Fix/fix register page
Syncfy/syncfy-frontend pull request #4
Opened 2023-11-09 19:20 UTC by Gabriel-Triceri

Registration page design change
Adding validation to the registration page

2023-11-09 23:20 UTC, shimarrudz requested changes

2023-11-09 23:20 UTC, shimarrudz commented on Syncfy/src/components/RegisterForm/index.tsx
> +import { CadastroButton } from '../CadastroButton';
Deixa os nomes dos "components" e das telas como Register form e Register pra ter coesão

2023-11-09 23:20 UTC, shimarrudz commented on Syncfy/src/screens/Register/index.tsx
> +export default Cadastro;
Deixa "Register"

2023-11-10 17:59 UTC, Gabriel-Triceri commented on Syncfy/src/screens/Register/index.tsx
> +export default Cadastro;
Resolvido

2023-11-10 17:59 UTC, Gabriel-Triceri commented on Syncfy/src/components/RegisterForm/index.tsx
> +import { CadastroButton } from '../CadastroButton';
Resolvido

2023-11-11 16:40 UTC, shimarrudz approved these changes

2023-11-11 16:43 UTC, matheusPierro approved these changes

2023-11-11 16:45 UTC, merged